version: '3.7'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      # - bundle_path:/bundle
    # environment:
    #   - BUNDLE_PATH=/bundle/vendor
    #   - BUNDLE_APP_CONFIG=/app/.bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

# volumes:
#   bundle_path:
