default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

# production:
#   <<: *default
#   database: app_production
#   username: app
#   password: <%= ENV['APP_DATABASE_PASSWORD'] %>
